version: '3'
networks:
  zookeeper-networks:
    driver: bridge
  kafka-networks:
    driver: bridge
  hbase-networks:
    driver: bridge

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    restart: always
    ports:
      - "9001:2181"
    volumes:
      - "/Users/damon/projects/docker/zookeeper/zookeeper1/data:/data"
      - "/Users/damon/projects/docker/zookeeper/zookeeper1/datalog:/datalog"
      - "/Users/damon/projects/docker/zookeeper/zookeeper1/logs:/logs"
      - "/Users/damon/projects/docker/zookeeper/zookeeper1/conf:/conf"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888
    networks:
      - zookeeper-networks

  zookeeper2:
    image: wurstmeister/zookeeper
    container_name: zookeeper2
    restart: always
    ports:
      - "9002:2181"
    volumes:
      - "/Users/damon/projects/docker/zookeeper/zookeeper2/data:/data"
      - "/Users/damon/projects/docker/zookeeper/zookeeper2/datalog:/datalog"
      - "/Users/damon/projects/docker/zookeeper/zookeeper2/logs:/logs"
      - "/Users/damon/projects/docker/zookeeper/zookeeper2/conf:/conf"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888
    networks:
      - zookeeper-networks

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.106
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: "192.168.0.106:9001,192.168.0.106:9002"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-networks
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.106
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: "192.168.0.106:9001,192.168.0.106:9002"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-networks
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.106
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_ZOOKEEPER_CONNECT: "192.168.0.106:9001,192.168.0.106:9002"
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-networks
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16000:16000"
    environment:
      HBASE_ZOOKEEPER_CONNECT: "192.168.0.106:9001,192.168.0.106:9002"
    networks:
      - hbase-networks

volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
